version: '3'

services:
  postgres:
    container_name: postgres_container
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: cloud_storage_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  adminer:
    container_name: adminer_container
    image: adminer
    restart: always
    ports:
      - '8081:8080'
  redis:
    container_name: redis_container
    image: redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    restart: always
    volumes:
      - redis-data:/data
  minio:
    container_name: minio_container
    image: minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-storage:/data
      - minio-config:/root/.minio
    command: server /data --console-address ":9001"

volumes:
  pg_data:
  redis-data:
  minio-storage:
  minio-config:
