version: '3'

services:
  postgres:
    container_name: postgres_container
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: cloud_storage_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
  adminer:
    container_name: adminer_container
    image: adminer
    restart: always
    ports:
      - '8081:8080'
  redis:
    container_name: redis_container
    image: redis
    environment:
      REDIS_USER: ${REDIS_USER}
      REDIS_USER_PASSWORD: ${REDIS_USER_PASSWORD}
    restart: always
    ports:
      - '6379:6379'
  minio:
    ports:
      - "9000:9000"
      - "9001:9001"
volumes:
  pg_data:
