version: '3'

services:
  postgres:
    container_name: postgres_container
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: cloud_storage_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
  adminer:
    container_name: adminer_container
    image: adminer
    restart: always
    ports:
      - '8081:8080'
  redis:
    container_name: redis_container
    image: redis
    restart: always
volumes:
  pg_data:
