spring:
  application:
    name: CloudStorage

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cloud_storage_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  liquibase:
    enabled: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

  mvc:
    hidden method:
      filter:
        enabled: true

  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}

  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB
      file-size-threshold: 0


minio:
  url: http://localhost:9000
  access-key: ${MINIO_ROOT_USER}
  secret-key: ${MINIO_ROOT_PASSWORD}

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    session:
      cookie:
        name: SESSION
