spring:
  application:
    name: CloudStorage

  #Datasource Configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/cloud_storage_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  #Hibernate configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

  #HiddenHttpFilter Configuration
  mvc:
    hidden method:
      filter:
        enabled: true

  #Redis
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}

  #Spring Session
  session:
    timeout: 7d

  logging:
    level:
      org.springframework.session: DEBUG