--liquibase formatted sql

--changeset walkmanx21:1
CREATE TABLE IF NOT EXISTS Resources (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    user_id INTEGER REFERENCES Users(id),
    resource VARCHAR NOT NULL
);

CREATE INDEX user_resource ON Resources (user_id, resource);