--liquibase formatted sql

--changeset walkmanx21:1
CREATE TABLE IF NOT EXISTS Users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    username VARCHAR(128) NOT NULL UNIQUE ,
    password uuid NOT NULL ,
    role VARCHAR(128) NOT NULL
);